### ISSUE TITLE
Error when loading into space battle

### ISSUE THREAD

**Issue by Duckyclaw** [MegaLP/factory#1]
![Screenshot_2022-12-05-20-25-42-48_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/119755396/205736498-40adf4f0-fac9-485c-acc0-50132225733f.jpg)

**Comment by Duckyclaw** [comment]
I have no idea what this error is

**Comment by MegaLP** [comment]
Well this shuld be fixed now!
